In [2]:
import os
os.getcwd()

'C:\\Users\\Precious Olalere\\Documents\\IS 567 Text Mining'

In [3]:
import pandas as pd

In [4]:
#Task 1: Load the dataset
#List down the number of statements in the training set and the test set

train_liar = pd.read_csv("LIAR_train.csv")
test_liar = pd.read_csv("LIAR_test.csv")


print ("Train set: ",len(train_liar))
print ("Test set: ",len(test_liar))

train_liar.head(10)

Train set:  10240
Test set:  1267


Unnamed: 0        label                                          statement  \
0           0        false  Says the Annies List political group supports ...   
1           1    half-true  When did the decline of coal start? It started...   
2           2  mostly-true  Hillary Clinton agrees with John McCain "by vo...   
3           3        false  Health care reform legislation is likely to ma...   
4           4    half-true  The economic turnaround started at the end of ...   
5           5         true  The Chicago Bears have had more starting quart...   
6           6  barely-true  Jim Dunnam has not lived in the district he re...   
7           7    half-true  I'm the only person on this stage who has work...   
8           8    half-true  However, it took $19.5 million in Oregon Lotte...   
9           9  mostly-true  Says GOP primary opponents Glenn Grothman and ...   

                                       topic                 speaker  \
0                                   abortion            dwayne-bohac   
1         energy,history,job-accomplishments          scott-surovell   
2                             foreign-policy            barack-obama   
3                                health-care            blog-posting   
4                               economy,jobs           charlie-crist   
5                                  education               robin-vos   
6                       candidates-biography  republican-party-texas   
7                                     ethics            barack-obama   
8                                       jobs          oregon-lottery   
9  energy,message-machine-2014,voting-record           duey-stroebel   

                      context   location         party  \
0        State representative      Texas    republican   
1              State delegate   Virginia      democrat   
2                   President   Illinois      democrat   
3                         NaN        NaN          none   
4                         NaN    Florida      democrat   
5  Wisconsin Assembly speaker  Wisconsin    republican   
6                         NaN      Texas    republican   
7                   President   Illinois      democrat   
8                         NaN        NaN  organization   
9        State representative  Wisconsin    republican   

                                   resource  
0                                  a mailer  
1                           a floor speech.  
2                                    Denver  
3                            a news release  
4                       an interview on CNN  
5                 a an online opinion-piece  
6                          a press release.  
7  a Democratic debate in Philadelphia, Pa.  
8                                a website   
9                           an online video

In [5]:
test_liar.head(10)

Unnamed: 0        label                                          statement  \
0           0         true  Building a wall on the U.S.-Mexico border will...   
1           1        false  Wisconsin is on pace to double the number of l...   
2           2        false  Says John McCain has done nothing to help the ...   
3           3    half-true  Suzanne Bonamici supports a plan that will cut...   
4           4   pants-fire  When asked by a reporter whether hes at the ce...   
5           5         true  Over the past five years the federal governmen...   
6           6         true  Says that Tennessee law requires that schools ...   
7           7  barely-true  Says Vice President Joe Biden "admits that the...   
8           8         true  Donald Trump is against marriage equality. He ...   
9           9  barely-true  We know that more than half of Hillary Clinton...   

                                               topic  \
0                                        immigration   
1                                               jobs   
2                    military,veterans,voting-record   
3  medicare,message-machine-2012,campaign-adverti...   
4  campaign-finance,legal-issues,campaign-adverti...   
5                 federal-budget,pensions,retirement   
6    county-budget,county-government,education,taxes   
7                                   economy,stimulus   
8                         gays-and-lesbians,marriage   
9                                     foreign-policy   

                            speaker  \
0                        rick-perry   
1                 katrina-shankland   
2                      donald-trump   
3                     rob-cornilles   
4  state-democratic-party-wisconsin   
5                   brendan-doherty   
6          stand-children-tennessee   
7                      john-boehner   
8              sean-patrick-maloney   
9                        mike-pence   

                                      context      location       party  \
0                                    Governor         Texas  republican   
1                        State representative     Wisconsin    democrat   
2                             President-Elect      New York  republican   
3                                  consultant        Oregon  republican   
4                                         NaN     Wisconsin    democrat   
5                                         NaN  Rhode Island  republican   
6  Child and education advocacy organization.     Tennessee        none   
7     Speaker of the House of Representatives          Ohio  republican   
8                       Congressman for NY-18      New York    democrat   
9                                    Governor       Indiana  republican   

                                         resource  
0                                 Radio interview  
1                               a news conference  
2                    comments on ABC's This Week.  
3                                    a radio show  
4                                     a web video  
5                              a campaign website  
6                          in a post on Facebook.  
7                                a press release.  
8  a speech at the Democratic National Convention  
9                    comments on "Meet the Press"

In [14]:
# enriching the statement for train dataset
def enrich_statement(row):
    return (f"{row['statement']} The topic of the statement is {row['topic']}. "
            f"The speaker is {row['speaker']}. The location is {row['location']}. "
            f"The party is {row['party']}. The statement comes from a {row['context']}.")

train_liar['enriched_statement'] = train_liar.apply(enrich_statement, axis=1)
pd.set_option('display.max_colwidth', None)
train_liar[["statement", "enriched_statement"]].head(5)


statement  \
0                                                             Says the Annies List political group supports third-trimester abortions on demand.   
1  When did the decline of coal start? It started when natural gas took off that started to begin in (President George W.) Bushs administration.   
2                                      Hillary Clinton agrees with John McCain "by voting to give George Bush the benefit of the doubt on Iran."   
3                                                                 Health care reform legislation is likely to mandate free sex change surgeries.   
4                                                                                         The economic turnaround started at the end of my term.   

                                                                                                                                                                                                                                                                                                                           enriched_statement  
0                                                                                    Says the Annies List political group supports third-trimester abortions on demand. The topic of the statement is abortion. The speaker is dwayne-bohac. The location is Texas. The party is republican. The statement comes from a State representative.  
1  When did the decline of coal start? It started when natural gas took off that started to begin in (President George W.) Bushs administration. The topic of the statement is energy,history,job-accomplishments. The speaker is scott-surovell. The location is Virginia. The party is democrat. The statement comes from a State delegate.  
2                                                                 Hillary Clinton agrees with John McCain "by voting to give George Bush the benefit of the doubt on Iran." The topic of the statement is foreign-policy. The speaker is barack-obama. The location is Illinois. The party is democrat. The statement comes from a President.  
3                                                                                                              Health care reform legislation is likely to mandate free sex change surgeries. The topic of the statement is health-care. The speaker is blog-posting. The location is nan. The party is none. The statement comes from a nan.  
4                                                                                                                            The economic turnaround started at the end of my term. The topic of the statement is economy,jobs. The speaker is charlie-crist. The location is Florida. The party is democrat. The statement comes from a nan.

#Here are 3 statements example before and after enrichment was performed on the training data. 

Before enrichment:Says the Annies List political group supports third-trimester abortions on demand.

After enrinchment: Says the Annies List political group supports third-trimester abortions on demand. The topic of the statement is abortion. The speaker is dwayne-bohac. The location is Texas. The party is republican. The statement comes from a State representative.

Before enrichment: When did the decline of coal start? It started when natural gas took off that started to begin in (President George W.) Bushs administration.

After Enrichment: When did the decline of coal start? It started when natural gas took off that started to begin in (President George W.) Bushs administration. The topic of the statement is energy,history,job-accomplishments. The speaker is scott-surovell. The location is Virginia. The party is democrat. The statement comes from a State delegate

Before enrichment: Hillary Clinton agrees with John McCain "by voting to give George Bush the benefit of the doubt on Iran."

After enrichment: Hillary Clinton agrees with John McCain "by voting to give George Bush the benefit of the doubt on Iran." The topic of the statement is foreign-policy. The speaker is barack-obama. The location is Illinois. The party is democrat. The statement comes from a President


In [15]:
# Enriching the statement for test dataset
def enrich_statement(row):
    return (f"{row['statement']} The topic of the statement is {row['topic']}. "
            f"The speaker is {row['speaker']}. The location is {row['location']}. "
            f"The party is {row['party']}. The statement comes from a {row['context']}.")

test_liar['enriched_statement'] = test_liar.apply(enrich_statement, axis=1)
test_liar[["statement", "enriched_statement"]].head(5)


statement  \
0                                                             Building a wall on the U.S.-Mexico border will take literally years.   
1                                                                  Wisconsin is on pace to double the number of layoffs this year.   
2                                                                              Says John McCain has done nothing to help the vets.   
3                                            Suzanne Bonamici supports a plan that will cut choice for Medicare Advantage seniors.   
4  When asked by a reporter whether hes at the center of a criminal scheme to violate campaign laws, Gov. Scott Walker nodded yes.   

                                                                                                                                                                                                                                                                                                                                     enriched_statement  
0                                                                                                                       Building a wall on the U.S.-Mexico border will take literally years. The topic of the statement is immigration. The speaker is rick-perry. The location is Texas. The party is republican. The statement comes from a Governor.  
1                                                                                                              Wisconsin is on pace to double the number of layoffs this year. The topic of the statement is jobs. The speaker is katrina-shankland. The location is Wisconsin. The party is democrat. The statement comes from a State representative.  
2                                                                                                        Says John McCain has done nothing to help the vets. The topic of the statement is military,veterans,voting-record. The speaker is donald-trump. The location is New York. The party is republican. The statement comes from a President-Elect.  
3                                                         Suzanne Bonamici supports a plan that will cut choice for Medicare Advantage seniors. The topic of the statement is medicare,message-machine-2012,campaign-advertising. The speaker is rob-cornilles. The location is Oregon. The party is republican. The statement comes from a consultant.  
4  When asked by a reporter whether hes at the center of a criminal scheme to violate campaign laws, Gov. Scott Walker nodded yes. The topic of the statement is campaign-finance,legal-issues,campaign-advertising. The speaker is state-democratic-party-wisconsin. The location is Wisconsin. The party is democrat. The statement comes from a nan.

#Here are 3 statements example before and after enrichment was performed on the test data.

Before enrichment: Building a wall on the U.S.-Mexico border will take literally years.
After enrichment: Building a wall on the U.S.-Mexico border will take literally years. The topic of the statement is immigration. The speaker is rick-perry. The location is Texas. The party is republican. The statement comes from a Governor.

Before enrichment: Wisconsin is on pace to double the number of layoffs this year.
After enrichment: Wisconsin is on pace to double the number of layoffs this year. The topic of the statement is jobs. The speaker is katrina-shankland. The location is Wisconsin. The party is democrat. The statement comes from a State representative

Before enrichment: Says John McCain has done nothing to help the vets.
Says John McCain has done nothing to help the vets. The topic of the statement is military,veterans,voting-record. The speaker is donald-trump. The location is New York. The party is republican. The statement comes from a President-Elect.

In [16]:
#Task 3: Extract unigram features
from sklearn.feature_extraction.text import CountVectorizer

train_text = train_liar["enriched_statement"]
test_text = test_liar["enriched_statement"]

# set the n-gram range
vectorizer = CountVectorizer(ngram_range = (1,1))

# create training data representation
train_data_cv = vectorizer.fit_transform(train_text.values.astype('U'))
print(train_data_cv.shape,"\n") 

# create test data representation
test_data_cv = vectorizer.transform(test_text.values.astype('U'))
print(test_data_cv.shape,"\n") 





(10240, 14216) 

(1267, 14216) 



In [17]:
#Task 4: Train and evaluate classifier

from sklearn.naive_bayes import MultinomialNB
# define true labels from train set
x_train = train_data_cv
y_train = train_liar["label"]
x_test = test_data_cv
y_test = test_liar["label"]

# build model on the training data
model = MultinomialNB()
model.fit(x_train, y_train)

# predict the labels for the test data
predictions = model.predict(x_test)

In [18]:
import pickle

# save the model to disk
filename = 'NaiveBayesModelBOW.sav'
pickle.dump(model, open(filename, 'wb'))

# some time later...
# load the model from disk
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.score(x_test, y_test)
print(result)

0.27466456195737965


In [20]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import classification_report, confusion_matrix 

print ("Accuracy score: ", accuracy_score(y_test, predictions))
print ("Individual label performance: ")
print (classification_report(y_test, predictions))
print (confusion_matrix(y_test, predictions))

Accuracy score:  0.27466456195737965
Individual label performance: 
              precision    recall  f1-score   support

 barely-true       0.22      0.14      0.17       212
       false       0.27      0.35      0.30       249
   half-true       0.27      0.36      0.31       265
 mostly-true       0.27      0.33      0.30       241
  pants-fire       0.46      0.12      0.19        92
        true       0.35      0.23      0.27       208

    accuracy                           0.27      1267
   macro avg       0.30      0.25      0.26      1267
weighted avg       0.29      0.27      0.27      1267

[[29 58 65 38  3 19]
 [30 86 57 43  7 26]
 [30 58 95 66  1 15]
 [17 40 79 80  0 25]
 [13 37 11 16 11  4]
 [13 42 50 54  2 47]]


In [19]:
#Task 5: Add bigram features

from sklearn.feature_extraction.text import CountVectorizer

train_text2 = train_liar["enriched_statement"]
test_text2 = test_liar["enriched_statement"]

# set the n-gram range
vectorizer = CountVectorizer(ngram_range = (1,2))

# create training data representation
train_data_cv2 = vectorizer.fit_transform(train_text2.values.astype('U'))
print(train_data_cv2.shape,"\n") 

# create test data representation
test_data_cv2 = vectorizer.transform(test_text2.values.astype('U'))
print(test_data_cv2.shape,"\n") 


(10240, 110514) 

(1267, 110514) 



In [20]:
#Repeat task 4 for task 5
# define true labels from train set
x_train2 = train_data_cv2
y_train2 = train_liar["label"]
x_test2 = test_data_cv2
y_test2 = test_liar["label"]

# build model on the training data
model = MultinomialNB()
model.fit(x_train2, y_train2)

# predict the labels for the test data
predictions2 = model.predict(x_test2)

In [21]:
#save the model to disk
filename = 'NaiveBayesModelBOW.sav'
pickle.dump(model, open(filename, 'wb'))

# some time later...
# load the model from disk
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.score(x_test2, y_test2)
print(result)

0.26045777426992894


In [51]:
#calculating performance metrics for task 5
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import classification_report, confusion_matrix 
print ("Accuracy score: ", accuracy_score(y_test2, predictions2))
print ("Individual label performance: ")
print (classification_report(y_test2, predictions2))
print (confusion_matrix(y_test2, predictions2))

Accuracy score:  0.26045777426992894
Individual label performance: 
              precision    recall  f1-score   support

 barely-true       0.21      0.06      0.09       212
       false       0.28      0.39      0.32       249
   half-true       0.25      0.48      0.32       265
 mostly-true       0.26      0.30      0.28       241
  pants-fire       0.00      0.00      0.00        92
        true       0.35      0.11      0.16       208

    accuracy                           0.26      1267
   macro avg       0.22      0.22      0.20      1267
weighted avg       0.25      0.26      0.23      1267

[[ 13  63  87  43   0   6]
 [ 15  97  87  40   0  10]
 [ 14  60 126  57   0   8]
 [  7  39 110  72   0  13]
 [ 11  47  19  12   0   3]
 [  2  44  82  58   0  22]]


C:\Users\Precious Olalere\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Precious Olalere\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Precious Olalere\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [22]:
#Task 6: Add trigram features

train_text3 = train_liar["enriched_statement"]
test_text3 = test_liar["enriched_statement"]

# set the n-gram range
vectorizer = CountVectorizer(ngram_range = (1,3))

# create training data representation
train_data_cv3 = vectorizer.fit_transform(train_text3.values.astype('U'))
print(train_data_cv3.shape,"\n") 

# create test data representation
test_data_cv3 = vectorizer.transform(test_text3.values.astype('U'))
print(test_data_cv3.shape,"\n") 



(10240, 271651) 

(1267, 271651) 



In [23]:
#Performing task 4 on task 6
# define true labels from train set
x_train3 = train_data_cv3
y_train3 = train_liar["label"]
x_test3 = test_data_cv3
y_test3 = test_liar["label"]

# build model on the training data
model = MultinomialNB()
model.fit(x_train3, y_train3)

# predict the labels for the test data
predictions3 = model.predict(x_test3)

In [24]:
#save the model to disk
filename = 'NaiveBayesModelBOW.sav'
pickle.dump(model, open(filename, 'wb'))

# some time later...
# load the model from disk
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.score(x_test3, y_test3)
print(result)

0.265982636148382


In [55]:
#calculating performance metrics for task 6
print ("Accuracy score: ", accuracy_score(y_test, predictions3))
print ("Individual label performance: ")
print (classification_report(y_test3, predictions3))
print (confusion_matrix(y_test3, predictions3))

Accuracy score:  0.265982636148382
Individual label performance: 
              precision    recall  f1-score   support

 barely-true       0.17      0.03      0.05       212
       false       0.28      0.42      0.34       249
   half-true       0.24      0.50      0.33       265
 mostly-true       0.26      0.29      0.28       241
  pants-fire       0.00      0.00      0.00        92
        true       0.44      0.12      0.18       208

    accuracy                           0.27      1267
   macro avg       0.23      0.23      0.20      1267
weighted avg       0.26      0.27      0.23      1267

[[  6  68  93  42   0   3]
 [  6 104  94  38   0   7]
 [  8  63 132  56   0   6]
 [  6  40 113  71   0  11]
 [  6  50  23  10   0   3]
 [  3  44  84  53   0  24]]


C:\Users\Precious Olalere\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Precious Olalere\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Precious Olalere\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [25]:
from sklearn.feature_extraction.text import TfidfVectorizer

# this time, we vectorize using TF-IDF
text = train_liar.iloc[0:3]["enriched_statement"]
print(text,"\n")

tf = TfidfVectorizer()
tf.fit(text)

print(tf.vocabulary_,"\n")

# encode document
data = tf.transform(text)

# summarize encoded vector
print(data.shape,"\n") 
print(data.toarray())

0                                                                                      Says the Annies List political group supports third-trimester abortions on demand. The topic of the statement is abortion. The speaker is dwayne-bohac. The location is Texas. The party is republican. The statement comes from a State representative.
1    When did the decline of coal start? It started when natural gas took off that started to begin in (President George W.) Bushs administration. The topic of the statement is energy,history,job-accomplishments. The speaker is scott-surovell. The location is Virginia. The party is democrat. The statement comes from a State delegate.
2                                                                   Hillary Clinton agrees with John McCain "by voting to give George Bush the benefit of the doubt on Iran." The topic of the statement is foreign-policy. The speaker is barack-obama. The location is Illinois. The party is democrat. The statement comes from a Pre

In [26]:
#Task 7: Add TF-IDF features
from sklearn.feature_extraction.text import TfidfVectorizer

#Feature Extraction using TfidfVectorizer for training and testing data on Review
train_data_tfidf = tf.fit_transform(train_text)
print(train_data_tfidf.shape,"\n") 

test_data_tfidf = tf.transform(test_text)
print(test_data_tfidf.shape,"\n") 

idf = tf.idf_

# print out feature names (the words) and the IDF values
print(dict(zip(tf.get_feature_names_out(), idf)))


(10240, 14216) 

(1267, 14216) 

{'00': 9.135542261407329, '000': 3.766455823971084, '000new': 9.541007369515492, '014': 9.541007369515492, '02': 9.135542261407329, '024': 9.541007369515492, '029': 9.541007369515492, '033': 9.541007369515492, '036': 9.541007369515492, '04': 9.541007369515492, '05': 8.847860188955547, '050': 9.541007369515492, '054th': 9.541007369515492, '06': 8.847860188955547, '07': 9.135542261407329, '075': 9.541007369515492, '08': 9.541007369515492, '081': 9.541007369515492, '09': 8.847860188955547, '092': 9.541007369515492, '095': 9.541007369515492, '10': 4.543795095751378, '100': 5.184298542825901, '100th': 9.541007369515492, '102': 9.541007369515492, '103': 9.135542261407329, '104': 8.847860188955547, '105': 8.847860188955547, '106': 9.135542261407329, '107': 9.135542261407329, '1070': 9.135542261407329, '108': 9.541007369515492, '109': 9.541007369515492, '10932': 9.541007369515492, '10th': 8.288244401020124, '11': 5.9574884310593825, '110': 8.288244401020124, '1

In [28]:
#performing task 4 on task 7
# define true labels from train set
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import classification_report, confusion_matrix 

x_train = train_data_tfidf
y_train = train_liar["label"]
x_test = test_data_tfidf
y_test = test_liar["label"]


model = MultinomialNB()
model.fit(x_train, y_train)
predictions = model.predict(x_test)

print ("Accuracy score: ", accuracy_score(y_test, predictions))
print ("Individual label performance: ")
print (classification_report(y_test, predictions))
print (confusion_matrix(y_test, predictions))

Accuracy score:  0.2573007103393844
Individual label performance: 
              precision    recall  f1-score   support

 barely-true       0.09      0.00      0.01       212
       false       0.27      0.34      0.30       249
   half-true       0.24      0.64      0.35       265
 mostly-true       0.28      0.27      0.28       241
  pants-fire       0.00      0.00      0.00        92
        true       0.38      0.02      0.05       208

    accuracy                           0.26      1267
   macro avg       0.21      0.21      0.16      1267
weighted avg       0.24      0.26      0.19      1267

[[  1  51 133  25   0   2]
 [  3  84 117  43   0   2]
 [  2  48 170  44   0   1]
 [  3  34 135  66   0   3]
 [  2  50  30  10   0   0]
 [  0  41 114  48   0   5]]


C:\Users\Precious Olalere\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Precious Olalere\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Precious Olalere\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [29]:
#Task 8:  Preprocess the data and apply the best-performing model
#Preprocess the statement column using one of the text preprocessing methods introduced earlier
#(e.g. stemming, stopword removal). You can store the preprocessed text in a new column. 
#Using NLTK to tokenize the enriched statement for train dataset(enriched statement & tokenized_enriched_statement column). 

#to carry out stop wprd removal tokenization has to been done first. 
import nltk
from nltk.tokenize import word_tokenize
train_liar["tokenized_enriched_statement"] = train_liar["enriched_statement"].apply(word_tokenize)
train_liar[["enriched_statement","tokenized_enriched_statement"]].head(10)

enriched_statement  \
0                                                                                          Says the Annies List political group supports third-trimester abortions on demand. The topic of the statement is abortion. The speaker is dwayne-bohac. The location is Texas. The party is republican. The statement comes from a State representative.   
1        When did the decline of coal start? It started when natural gas took off that started to begin in (President George W.) Bushs administration. The topic of the statement is energy,history,job-accomplishments. The speaker is scott-surovell. The location is Virginia. The party is democrat. The statement comes from a State delegate.   
2                                                                       Hillary Clinton agrees with John McCain "by voting to give George Bush the benefit of the doubt on Iran." The topic of the statement is foreign-policy. The speaker is barack-obama. The location is Illinois. The party is democrat. The statement comes from a President.   
3                                                                                                                    Health care reform legislation is likely to mandate free sex change surgeries. The topic of the statement is health-care. The speaker is blog-posting. The location is nan. The party is none. The statement comes from a nan.   
4                                                                                                                                  The economic turnaround started at the end of my term. The topic of the statement is economy,jobs. The speaker is charlie-crist. The location is Florida. The party is democrat. The statement comes from a nan.   
5         The Chicago Bears have had more starting quarterbacks in the last 10 years than the total number of tenured (UW) faculty fired during the last two decades. The topic of the statement is education. The speaker is robin-vos. The location is Wisconsin. The party is republican. The statement comes from a Wisconsin Assembly speaker.   
6                                                                                                  Jim Dunnam has not lived in the district he represents for years now. The topic of the statement is candidates-biography. The speaker is republican-party-texas. The location is Texas. The party is republican. The statement comes from a nan.   
7                         I'm the only person on this stage who has worked actively just last year passing, along with Russ Feingold, some of the toughest ethics reform since Watergate. The topic of the statement is ethics. The speaker is barack-obama. The location is Illinois. The party is democrat. The statement comes from a President.   
8                                               However, it took $19.5 million in Oregon Lottery funds for the Port of Newport to eventually land the new NOAA Marine Operations Center-Pacific. The topic of the statement is jobs. The speaker is oregon-lottery. The location is nan. The party is organization. The statement comes from a nan.   
9  Says GOP primary opponents Glenn Grothman and Joe Leibham cast a compromise vote that cost $788 million in higher electricity costs. The topic of the statement is energy,message-machine-2014,voting-record. The speaker is duey-stroebel. The location is Wisconsin. The party is republican. The statement comes from a State representative.   

                                                                                                                                                                                                                                                                                                                                                                                              tokenized_enriched_statement  
0                                                                                                               [Says, the, Annies, Li

In [30]:
#Using NLTK to tokenize the enriched statement for test dataset(enriched statement & tokenized_enriched_statement column). 

import nltk
from nltk.tokenize import word_tokenize
test_liar["tokenized_enriched_statement"] = test_liar["enriched_statement"].apply(word_tokenize)
test_liar[["enriched_statement","tokenized_enriched_statement"]].head(10)

enriched_statement  \
0                                                                                                                                                                           Building a wall on the U.S.-Mexico border will take literally years. The topic of the statement is immigration. The speaker is rick-perry. The location is Texas. The party is republican. The statement comes from a Governor.   
1                                                                                                                                                                  Wisconsin is on pace to double the number of layoffs this year. The topic of the statement is jobs. The speaker is katrina-shankland. The location is Wisconsin. The party is democrat. The statement comes from a State representative.   
2                                                                                                                                                            Says John McCain has done nothing to help the vets. The topic of the statement is military,veterans,voting-record. The speaker is donald-trump. The location is New York. The party is republican. The statement comes from a President-Elect.   
3                                                                                                             Suzanne Bonamici supports a plan that will cut choice for Medicare Advantage seniors. The topic of the statement is medicare,message-machine-2012,campaign-advertising. The speaker is rob-cornilles. The location is Oregon. The party is republican. The statement comes from a consultant.   
4                                                      When asked by a reporter whether hes at the center of a criminal scheme to violate campaign laws, Gov. Scott Walker nodded yes. The topic of the statement is campaign-finance,legal-issues,campaign-advertising. The speaker is state-democratic-party-wisconsin. The location is Wisconsin. The party is democrat. The statement comes from a nan.   
5                                                            Over the past five years the federal government has paid out $601 million in retirement and disability benefits to deceased former federal employees. The topic of the statement is federal-budget,pensions,retirement. The speaker is brendan-doherty. The location is Rhode Island. The party is republican. The statement comes from a nan.   
6  Says that Tennessee law requires that schools receive half of proceeds -- $31 million per year -- from a half-cent increase in the Shelby County sales tax. The topic of the statement is county-budget,county-government,education,taxes. The speaker is stand-children-tennessee. The location is Tennessee. The party is none. The statement comes from a Child and education advocacy organization..   
7                                                                                     Says Vice President Joe Biden "admits that the American people are being scammed" with the economic stimulus package. The topic of the statement is economy,stimulus. The speaker is john-boehner. The location is Ohio. The party is republican. The statement comes from a Speaker of the House of Representatives.   
8                                                                                                                                         Donald Trump is against marriage equality. He wants to go back. The topic of the statement is gays-and-lesbians,marriage. The speaker is sean-patrick-maloney. The location is New York. The party is democrat. The statement comes from a Congressman for NY-18.   
9                                                                                     We know that more than half of Hillary Clintons meetings while she was secretary of state were given to major contributors to the Clinton Foundation. The topic of the statement is foreign-policy. The speaker is mike-pence. The location is Indiana. The party is republican. The statement comes from a G

In [31]:
#removing stopword from train dataset 
from nltk.corpus import stopwords

stop_words = set(stopwords.words("english"))
def remove_stopwords(tokenized_text):
    return [word for word in tokenized_text if word not in stop_words]

train_liar["stopword_removed_statement"] = train_liar["tokenized_enriched_statement"].apply(remove_stopwords)
train_liar[["tokenized_enriched_statement", "stopword_removed_statement"]].head(10)


tokenized_enriched_statement  \
0                                                                                                               [Says, the, Annies, List, political, group, supports, third-trimester, abortions, on, demand, ., The, topic, of, the, statement, is, abortion, ., The, speaker, is, dwayne-bohac, ., The, location, is, Texas, ., The, party, is, republican, ., The, statement, comes, from, a, State, representative, .]   
1  [When, did, the, decline, of, coal, start, ?, It, started, when, natural, gas, took, off, that, started, to, begin, in, (, President, George, W., ), Bushs, administration, ., The, topic, of, the, statement, is, energy, ,, history, ,, job-accomplishments, ., The, speaker, is, scott-surovell, ., The, location, is, Virginia, ., The, party, is, democrat, ., The, statement, comes, from, a, State, delegate, .]   
2                                                                               [Hillary, Clinton, agrees, with, John, McCain, ``, by, voting, to, give, George, Bush, the, benefit, of, the, doubt, on, Iran, ., '', The, topic, of, the, statement, is, foreign-policy, ., The, speaker, is, barack-obama, ., The, location, is, Illinois, ., The, party, is, democrat, ., The, statement, comes, from, a, President, .]   
3                                                                                                                                         [Health, care, reform, legislation, is, likely, to, mandate, free, sex, change, surgeries, ., The, topic, of, the, statement, is, health-care, ., The, speaker, is, blog-posting, ., The, location, is, nan, ., The, party, is, none, ., The, statement, comes, from, a, nan, .]   
4                                                                                                                                                     [The, economic, turnaround, started, at, the, end, of, my, term, ., The, topic, of, the, statement, is, economy, ,, jobs, ., The, speaker, is, charlie-crist, ., The, location, is, Florida, ., The, party, is, democrat, ., The, statement, comes, from, a, nan, .]   
5         [The, Chicago, Bears, have, had, more, starting, quarterbacks, in, the, last, 10, years, than, the, total, number, of, tenured, (, UW, ), faculty, fired, during, the, last, two, decades, ., The, topic, of, the, statement, is, education, ., The, speaker, is, robin-vos, ., The, location, is, Wisconsin, ., The, party, is, republican, ., The, statement, comes, from, a, Wisconsin, Assembly, speaker, .]   
6                                                                                                                      [Jim, Dunnam, has, not, lived, in, the, district, he, represents, for, years, now, ., The, topic, of, the, statement, is, candidates-biography, ., The, speaker, is, republican-party-texas, ., The, location, is, Texas, ., The, party, is, republican, ., The, statement, comes, from, a, nan, .]   
7                         [I, 'm, the, only, person, on, this, stage, who, has, worked, actively, just, last, year, passing, ,, along, with, Russ, Feingold, ,, some, of, the, toughest, ethics, reform, since, Watergate, ., The, topic, of, the, statement, is, ethics, ., The, speaker, is, barack-obama, ., The, location, is, Illinois, ., The, party, is, democrat, ., The, statement, comes, from, a, President, .]   
8                                                     [However, ,, it, took, $, 19.5, million, in, Oregon, Lottery, funds, for, the, Port, of, Newport, to, eventually, land, the, new, NOAA, Marine, Operations, Center-Pacific, ., The, topic, of, the, statement, is, jobs, ., The, speaker, is, oregon-lottery, ., The, location, is, nan, ., The, party, is, organization, ., The, statement, comes, from, a, nan, .]   
9   [Says, GOP, primary, opponents, Glenn, Grothman, and, Joe, Leibham, cast, a, compromise, vote, that, cost, $, 788, million, in, higher, electricity, costs, ., The, topic, of, the, statement, is, energy, ,, message-machine-2014, ,, voting-

In [32]:
#removing stopword from test dataset 
from nltk.corpus import stopwords

stop_words = set(stopwords.words("english"))
def remove_stopwords(tokenized_text):
    return [word for word in tokenized_text if word not in stop_words]

test_liar["stopword_removed_statement"] = test_liar["tokenized_enriched_statement"].apply(remove_stopwords)
test_liar[["tokenized_enriched_statement", "stopword_removed_statement"]].head(10)


tokenized_enriched_statement  \
0                                                                                                                                                                                                             [Building, a, wall, on, the, U.S.-Mexico, border, will, take, literally, years, ., The, topic, of, the, statement, is, immigration, ., The, speaker, is, rick-perry, ., The, location, is, Texas, ., The, party, is, republican, ., The, statement, comes, from, a, Governor, .]   
1                                                                                                                                                                                                  [Wisconsin, is, on, pace, to, double, the, number, of, layoffs, this, year, ., The, topic, of, the, statement, is, jobs, ., The, speaker, is, katrina-shankland, ., The, location, is, Wisconsin, ., The, party, is, democrat, ., The, statement, comes, from, a, State, representative, .]   
2                                                                                                                                                                                      [Says, John, McCain, has, done, nothing, to, help, the, vets, ., The, topic, of, the, statement, is, military, ,, veterans, ,, voting-record, ., The, speaker, is, donald-trump, ., The, location, is, New, York, ., The, party, is, republican, ., The, statement, comes, from, a, President-Elect, .]   
3                                                                                                                                     [Suzanne, Bonamici, supports, a, plan, that, will, cut, choice, for, Medicare, Advantage, seniors, ., The, topic, of, the, statement, is, medicare, ,, message-machine-2012, ,, campaign-advertising, ., The, speaker, is, rob-cornilles, ., The, location, is, Oregon, ., The, party, is, republican, ., The, statement, comes, from, a, consultant, .]   
4                                                                [When, asked, by, a, reporter, whether, hes, at, the, center, of, a, criminal, scheme, to, violate, campaign, laws, ,, Gov, ., Scott, Walker, nodded, yes, ., The, topic, of, the, statement, is, campaign-finance, ,, legal-issues, ,, campaign-advertising, ., The, speaker, is, state-democratic-party-wisconsin, ., The, location, is, Wisconsin, ., The, party, is, democrat, ., The, statement, comes, from, a, nan, .]   
5                                                                       [Over, the, past, five, years, the, federal, government, has, paid, out, $, 601, million, in, retirement, and, disability, benefits, to, deceased, former, federal, employees, ., The, topic, of, the, statement, is, federal-budget, ,, pensions, ,, retirement, ., The, speaker, is, brendan-doherty, ., The, location, is, Rhode, Island, ., The, party, is, republican, ., The, statement, comes, from, a, nan, .]   
6  [Says, that, Tennessee, law, requires, that, schools, receive, half, of, proceeds, --, $, 31, million, per, year, --, from, a, half-cent, increase, in, the, Shelby, County, sales, tax, ., The, topic, of, the, statement, is, county-budget, ,, county-government, ,, education, ,, taxes, ., The, speaker, is, stand-children-tennessee, ., The, location, is, Tennessee, ., The, party, is, none, ., The, statement, comes, from, a, Child, and, education, advocacy, organization, ..]   
7                                                                                                 [Says, Vice, President, Joe, Biden, ``, admits, that, the, American, people, are, being, scammed, '', with, the, economic, stimulus, package, ., The, topic, of, the, statement, is, economy, ,, stimulus, ., The, speaker, is, john-boehner, ., The, location, is, Ohio, ., The, party, is, republican, ., The, statement, comes, from, a, Speaker, of, the, House, of, Representatives, .]   
8                                                                                                               

In [33]:
#Based on the model performance from task 3, 4, 5,. 
#The unigram model is the best performing model, therefore, I will be using it for the preprocessed text. 

#Extract unigram features
from sklearn.feature_extraction.text import CountVectorizer

train_text = train_liar["stopword_removed_statement"].apply(lambda x: " ".join(x))
test_text = test_liar["stopword_removed_statement"].apply(lambda x: " ".join(x))

# set the n-gram range
vectorizer = CountVectorizer(ngram_range = (1,1))

# create training data representation
train_data_cv = vectorizer.fit_transform(train_text.values.astype('U'))
print(train_data_cv.shape,"\n") 

# create test data representation
test_data_cv = vectorizer.transform(test_text.values.astype('U'))
print(test_data_cv.shape,"\n") 



(10240, 14183) 

(1267, 14183) 



In [34]:
#Train and evaluate classifier

from sklearn.naive_bayes import MultinomialNB
# define true labels from train set
x_train4 = train_data_cv
y_train4 = train_liar["label"]
x_test4 = test_data_cv
y_test4 = test_liar["label"]

# build model on the training data
model = MultinomialNB()
model.fit(x_train4, y_train4)

# predict the labels for the test data
predictions4 = model.predict(x_test4)

In [35]:
#save the model to disk
filename = 'NaiveBayesModelBOW.sav'
pickle.dump(model, open(filename, 'wb'))

# some time later...
# load the model from disk
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.score(x_test4, y_test4)
print(result)

0.2770323599052881


In [70]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import classification_report, confusion_matrix 

print ("Accuracy score: ", accuracy_score(y_test4, predictions4))
print ("Individual label performance: ")
print (classification_report(y_test4, predictions4))
print (confusion_matrix(y_test4, predictions4))

Accuracy score:  0.2770323599052881
Individual label performance: 
              precision    recall  f1-score   support

 barely-true       0.23      0.15      0.18       212
       false       0.28      0.36      0.31       249
   half-true       0.28      0.37      0.32       265
 mostly-true       0.26      0.31      0.28       241
  pants-fire       0.50      0.14      0.22        92
        true       0.32      0.22      0.26       208

    accuracy                           0.28      1267
   macro avg       0.31      0.26      0.26      1267
weighted avg       0.29      0.28      0.27      1267

[[31 58 62 36  4 21]
 [26 89 56 43  7 28]
 [28 55 98 67  1 16]
 [23 39 78 75  0 26]
 [15 34 11 14 13  5]
 [12 47 51 52  1 45]]


In [36]:
#Task 10: Error Analysis

predictions = predictions4
labels = test_liar["stopword_removed_statement"]
inputs = test_liar["label"]

# Limit number of examples to three
count = 0
max_examples = 5


for idx, prediction, label in zip(enumerate(inputs), predictions, labels):
    if prediction != label:
        print("Sample", 'has been classified as', prediction, 'and should be', label, idx) 
        print ("\n")
        count += 1
    if count >= max_examples:
        break

        

    

Sample has been classified as half-true and should be ['Building', 'wall', 'U.S.-Mexico', 'border', 'take', 'literally', 'years', '.', 'The', 'topic', 'statement', 'immigration', '.', 'The', 'speaker', 'rick-perry', '.', 'The', 'location', 'Texas', '.', 'The', 'party', 'republican', '.', 'The', 'statement', 'comes', 'Governor', '.'] (0, 'true')


Sample has been classified as half-true and should be ['Wisconsin', 'pace', 'double', 'number', 'layoffs', 'year', '.', 'The', 'topic', 'statement', 'jobs', '.', 'The', 'speaker', 'katrina-shankland', '.', 'The', 'location', 'Wisconsin', '.', 'The', 'party', 'democrat', '.', 'The', 'statement', 'comes', 'State', 'representative', '.'] (1, 'false')


Sample has been classified as false and should be ['Says', 'John', 'McCain', 'done', 'nothing', 'help', 'vets', '.', 'The', 'topic', 'statement', 'military', ',', 'veterans', ',', 'voting-record', '.', 'The', 'speaker', 'donald-trump', '.', 'The', 'location', 'New', 'York', '.', 'The', 'party', 're

In [37]:
#Task 11: Three-way vs six-way classification

# Assuming your original labels are in a column named 'label'
# Re-map labels to three categories: Negative, Neutral, Positive

group_label = {
    "pants-fire": "negative",
    "false": "negative",
    "barely-true": "neutral",
    "half-true": "neutral",
    "mostly-true": "positive",
    "true": 'positive'
}

# Apply the mapping to train and test dataset
train_liar["three_way"] = train_liar["label"].map(group_label)
test_liar["three_way"] = test_liar["label"].map(group_label)



In [38]:
from sklearn.feature_extraction.text import CountVectorizer

train_textnew = train_liar["stopword_removed_statement"].apply(lambda x: " ".join(x))
test_textnew = test_liar["stopword_removed_statement"].apply(lambda x: " ".join(x))

# set the n-gram range
vectorizer = CountVectorizer(ngram_range = (1,1))

# create training data representation
train_data_cv = vectorizer.fit_transform(train_textnew.values.astype('U'))
print(train_data_cv.shape,"\n") 

# create test data representation
test_data_cv = vectorizer.transform(test_textnew.values.astype('U'))
print(test_data_cv.shape,"\n") 


(10240, 14183) 

(1267, 14183) 



In [39]:
#Train and evaluate classifier

from sklearn.naive_bayes import MultinomialNB
# define true labels from train set
x_train5 = train_data_cv
y_train5 = train_liar["three_way"]
x_test5= test_data_cv
y_test5 = test_liar["three_way"]

# build model on the training data
model = MultinomialNB()
model.fit(x_train5, y_train5)

# predict the labels for the test data
predictions5 = model.predict(x_test5)

In [40]:
#save the model to disk
filename = 'NaiveBayesModelBOW.sav'
pickle.dump(model, open(filename, 'wb'))

# some time later...
# load the model from disk
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.score(x_test5, y_test5)
print(result)

0.4435674822415154


In [41]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import classification_report, confusion_matrix 

print ("Accuracy score: ", accuracy_score(y_test5, predictions5))
print ("Individual label performance: ")
print (classification_report(y_test5, predictions5))
print (confusion_matrix(y_test5, predictions5))

Accuracy score:  0.4435674822415154
Individual label performance: 
              precision    recall  f1-score   support

    negative       0.43      0.34      0.38       341
     neutral       0.43      0.45      0.44       477
    positive       0.47      0.51      0.49       449

    accuracy                           0.44      1267
   macro avg       0.44      0.44      0.44      1267
weighted avg       0.44      0.44      0.44      1267

[[116 130  95]
 [ 95 215 167]
 [ 58 160 231]]


The three way classification perfomed better than the six way classification. The f1 score of the six-way classification was so low compared to the three-way classification as well as the prediction accuracy. 

#Task 12 (Bonus): Perharps reducing the classification to two would help improve the performance of the model. So instead of 	Group labels ({pants-fire, false} -> negative, {barely true, half-true} -> neutral, {mostly true, and true} -> positive) to make it a three-way classification task. It would be group label-> Negative {barely true, half true, pants-fire, false} and Postive {mostly true, true}. 

We need more information that is beyond what is in the dataset because we are dealing with mis-information classification. We might probably also need a new model for accurate text classification. 